### ISSUE TITLE
Adding Sudoku solver Code in Backtracking repositry 

### ISSUE THREAD

**Issue by Himanshu-Agg12** [Sushreesatarupa/DSA-cpp#15]
Please assign the task to me, i will code in c++ language.

**Comment by arya177** [comment]
Please assign this issue to me. I code in C++ and can solve this problem.

**Comment by navjotdadwal** [comment]
sir can you please assign this issue to me i am current rated 5 star at codechef with rating of 2153 and rated expert at codeforces with rating of 1776 and i use cpp language for competitive programming and can resolve this issue

**Comment by Harshitbhatt69** [comment]
Its my project in 1st year. Can i add it please?

**Comment by Himanshu-Agg12** [comment]
Hello Mam, I have completed my Task please merge my pull requestIt is not conflicting with the current branch and also the change I have made are very useful for others.Thanks Sent from Mail for Windows From: Sushree SatarupaSent: Friday, October 1, 2021 10:25 AMTo: Sushreesatarupa/DSA-cpp-Hacktoberfest2021Cc: Himanshu Aggarwal; AssignSubject: Re: [Sushreesatarupa/DSA-cpp-Hacktoberfest2021] Adding Sudoku solver Code in Backtracking repositry (#15) Assigned #15 to @Himanshu-Agg12.—You are receiving this because you were assigned.Reply to this email directly, view it on GitHub, or unsubscribe.Triage notifications on the go with GitHub Mobile for iOS or Android.
