### ISSUE TITLE
Would like to add some more ways of sorting an array

### ISSUE THREAD

**Issue by varsha080** [Sushreesatarupa/DSA-cpp#17]

**Comment by Sanket2055** [comment]
Hello sir/ ma'am , I am participating in hacktoberfest 2021 , I would like to contribute code of a sorting algorithm(bubble sort) which is not present here , please allow me to go ahead and assign me this issue. Thank you , waiting for the reply

**Comment by navjotdadwal** [comment]
sir can you please assign this issue to me i am current rated 5 star at codechef with rating of 2153 and rated expert at codeforces with rating of 1776 and i use cpp language for competitive programming and can resolve this issue
