### ISSUE TITLE
In Dynamic Programming folder also, There are not any codes or file. 

### ISSUE THREAD

**Issue by Rajat-Jain29** [Sushreesatarupa/DSA-cpp#19]
@Sushreesatarupa I want to add some popular codes of Dynamic Programming in it. Please assign it to me, under the label Hacktoberfest 2021 :)

**Comment by navjotdadwal** [comment]
sir can you please assign this issue to me i am current rated 5 star at codechef with rating of 2153 and rated expert at codeforces with rating of 1776 and i use cpp language for competitive programming and can resolve this issue

**Comment by navjotdadwal** [comment]
thanks for assigning my favourite topic mam i can add many things in this
but i have made PR earlier so merge it so that i can contribute further

**Comment by HelloGit2309** [comment]
@Sushreesatarupa  please assign this issue to me. I am a competitve programmer and I would like to add some quality problems on dynamic programming.

**Comment by navjotdadwal** [comment]
maam please merge my PR #19
