### ISSUE TITLE
Solution to the bit manipulation problem find-the-number-that-appears-once 

### ISSUE THREAD

**Issue by Swayam221** [Sushreesatarupa/DSA-cpp#21]
I would like to provide a solution to the [element-appearing-once](https://practice.geeksforgeeks.org/problems/element-appearing-once2552/1) using bit manipulation.

Requesting to be assigned to this issue under the 'hacktoberfest2021' label. Thanks.

**Comment by navjotdadwal** [comment]
sir can you please assign this issue to me i am current rated 5 star at codechef with rating of 2153 and rated expert at codeforces with rating of 1776 and i use cpp language for competitive programming and can resolve this issue

**Comment by Harshitbhatt69** [comment]
Well this is interesting. Can i handle this issue?
