### ISSUE TITLE
[Technical Writing]: Searching and Sorting

### ISSUE THREAD

**Issue by hariketsheth** [Sushreesatarupa/DSA-cpp#220]
### Description

- Added Folders for Searching and Sorting
- Would like to add technical Writings for the following topics:
   - Searching / 
       1. Binary Search
   - Sorting /
       1. Selection Sort
       2. Merge Sort

### Domain

Searching

### Type of Contribution

Documentation

### Code of Conduct

- [X] I follow Contributing Guidelines & Code of conduct.

**Comment by anand722000** [comment]
I Have a new concept of Sorting, which i would like to Contribute so please assign me for this...
