### ISSUE TITLE
feat: add merge sort entire code in cpp

### ISSUE THREAD

**Issue by RoshanMhatre** [Sushreesatarupa/DSA-cpp#221]
### Description

Hey, I want to add the Merge Sort code in cpp since it is not there.
Please assign hacktoberfest label.

### Domain

Sorting

### Type of Contribution

Code

### Code of Conduct

- [X] I follow Contributing Guidelines & Code of conduct.

**Comment by yogesh-kansal** [comment]
@RoshanMhatre  Please assign this issue to me.
