### ISSUE TITLE
0-1Knapsack problem using recursion

### ISSUE THREAD

**Issue by shivam-0510** [Sushreesatarupa/DSA-cpp#268]
### Description

Given weights and values of n items, put these items in a knapsack of capacity W to get the maximum total value in the knapsack. In other words, given two integer arrays val[0..n-1] and wt[0..n-1] which represent values and weights associated with n items respectively. Also given an integer W which represents knapsack capacity, find out the maximum value subset of val[] such that sum of the weights of this subset is smaller than or equal to W. You cannot break an item, either pick the complete item or don’t pick it (0-1 property).

### Domain

Recursion

### Type of Contribution

Code

### Code of Conduct

- [X] I follow Contributing Guidelines & Code of conduct.

**Comment by shivam-0510** [comment]
@Sushreesatarupa Please assign this issue to me

**Comment by codelord09** [comment]
@Sushreesatarupa Please assign me this issue. Thank You

**Comment by imshukla10** [comment]
Please assign this problem to me

**Comment by p1yu5h0** [comment]
Please assign this to me. I want to add my submissions.
