### ISSUE TITLE
Sliding window maximum problem

### ISSUE THREAD

**Issue by yogesh-kansal** [Sushreesatarupa/DSA-cpp#276]
## Description
You are given an array of integers nums, there is a sliding window of size k which is moving from the very left of the array to the very right. You can only see the k numbers in the window. Each time the sliding window moves right by one position.

Return the max sliding window.

### Domain

Deque

### Type of Contribution

Code

### Code of Conduct

- [X] I follow Contributing Guidelines & Code of conduct.

**Comment by yogesh-kansal** [comment]
@Sushreesatarupa Please assign this issue to me

**Comment by imshukla10** [comment]
Pls assign this issue to me
