### ISSUE TITLE
Print concentric rectangular pattern in a 2d matrix

### ISSUE THREAD

**Issue by seikhchilli** [Sushreesatarupa/DSA-cpp#278]
### Description

Print concentric rectangular pattern in a 2d matrix

Given a positive integer n, print the matrix filled with rectangle pattern as shown below: 
a a a a a 
a b b b a 
a b c b a 
a b b b a 
a a a a a 
where a = n, b = n – 1,c = n – 2 and so on.

### Domain

Matrix

### Type of Contribution

Code

### Code of Conduct

- [X] I follow Contributing Guidelines & Code of conduct.

**Comment by seikhchilli** [comment]
please assign me this

**Comment by Harshgoel189** [comment]
Given an m x n matrix, return all elements of the matrix in spiral order.

 

Example 1:


Input: matrix = [[1,2,3],[4,5,6],[7,8,9]]
Output: [1,2,3,6,9,8,7,4,5]
Example 2:


Input: matrix = [[1,2,3,4],[5,6,7,8],[9,10,11,12]]
Output: [1,2,3,4,8,12,11,10,9,5,6,7]

I want to work on this question .Please assign this to me.
