### ISSUE TITLE
Adding two matrix

### ISSUE THREAD

**Issue by Harikrishnaa3131** [Sushreesatarupa/DSA-cpp#281]
In matrix folder there is only code for transpose of a matrix. I will add the code for adding two matrix using c++ to that folder. I would like to contribute to this issue under Hacktoberfest'2021. @Sushreesatarupa Kindly assign me this issue.

**Comment by Ishika-Jaiswal** [comment]
I can add the code for the addition of two matrices in C++ in the required folder, and I would like to contribute to this issue under Hacktoberfest'21, so @Sushreesatarupa Can you please assign me this issue?

**Comment by avyayjain** [comment]
pls assign me this issue
