### ISSUE TITLE
Code for Inverting a Binary Search Tree

### ISSUE THREAD

**Issue by rushendra910** [Sushreesatarupa/DSA-cpp#29]
I would like to add a code for inverting a Binary Search Tree under the corresponding directory.

Please assign this issue to me under the 'hacktoberfest2021' tag.

**Comment by Prajakta102** [comment]
I would like to add a code for inverting a Binary Search Tree under the corresponding directory.

Please assign this issue to me under the 'hacktoberfest2021' tag.

**Comment by navjotdadwal** [comment]
sir can you please assign this issue to me i am current rated 5 star at codechef with rating of 2153 and rated expert at codeforces with rating of 1776 and i use cpp language for competitive programming and can resolve this issue

**Comment by Harshitbhatt69** [comment]
Hey, I had done this question yesterday in leetcode. Can i handle this issue?
