### ISSUE TITLE
Best Time to Buy and Sell Stocks -3

### ISSUE THREAD

**Issue by mrkc2303** [Sushreesatarupa/DSA-cpp#290]
### Description

Will add solution to Best Time to Buy and Sell Stocks - 3 using C++

### Domain

Arrays

### Type of Contribution

Code

### Code of Conduct

- [X] I follow Contributing Guidelines & Code of conduct.

**Comment by mrkc2303** [comment]
Kindly Assign me this for HacktoberFest 2021

**Comment by Harshgoel189** [comment]
Best Time to Buy and Sell Stock IV

I want to propose the solution of this question and want to make a PR.Please assign me this.
