### ISSUE TITLE
Merge linked lists

### ISSUE THREAD

**Issue by Nithish2032** [Sushreesatarupa/DSA-cpp#294]
### Description

Hey. I want to add a program that merges two sorted linked lists into one. Please add hacktoberfest label.

### Domain

Arrays

### Type of Contribution

Code

### Code of Conduct

- [X] I follow Contributing Guidelines & Code of conduct.

**Comment by rebelfire888** [comment]
I would like to work on this issue

**Comment by sreejan774** [comment]
I am an hacktober fest participant I would like to solve this issue.
