### ISSUE TITLE
Add programs in the Greedy algorithm

### ISSUE THREAD

**Issue by MilanAgrawal** [Sushreesatarupa/DSA-cpp#30]
I would like to add some good programs for greedy and DP.
Requesting to be assigned to this issue under the 'hacktoberfest2021' label. Thanks.

**Comment by Prajakta102** [comment]
I would like to add solution to this problem please assign this task to me

**Comment by navjotdadwal** [comment]
sir can you please assign this issue to me i am current rated 5 star at codechef with rating of 2153 and rated expert at codeforces with rating of 1776 and i use cpp language for competitive programming and can resolve this issue

**Comment by HelloGit2309** [comment]
@Sushreesatarupa please assign this issue to me. I am a competitive programmer and I want to contribute in resolving this issue. I would like to add some greedy problems.

**Comment by Harshgupta5901** [comment]
hey please assign this issue to me I would add some good problems of greedy algorithm
@Sushreesatarupa

**Comment by p1yu5h0** [comment]
Hello, Please assign this issue to me. I would love to contribute some greedy programs!!
