### ISSUE TITLE
Intersection of two sorted arrays 

### ISSUE THREAD

**Issue by pawangupta5167** [Sushreesatarupa/DSA-cpp#301]
### Description

Hey, I want to add a Program to find the intersection of two sorted arrays using fuctions. Please assign it to me under Hactoberfest 2021.

### Domain

Arrays

### Type of Contribution

Code

### Code of Conduct

- [X] I follow Contributing Guidelines & Code of conduct.

**Comment by rebelfire888** [comment]
I would like to work on this issue.

**Comment by madildev** [comment]
Hi, I would like to work on this issue can you assign this to me
