### ISSUE TITLE
Maximum absolute difference

### ISSUE THREAD

**Issue by pawangupta5167** [Sushreesatarupa/DSA-cpp#305]
### Description

Program to find maximum absolute difference using arrays. Please assign it under Hactoberfest.

### Domain

Arrays

### Type of Contribution

Code

### Code of Conduct

- [X] I follow Contributing Guidelines & Code of conduct.

**Comment by AbhayG01** [comment]
I have good knowledge of Data Structures and Algorithms, please assign this issue to me.
