### ISSUE TITLE
[Create New Issue]: Breadth First Search Binary Tree

### ISSUE THREAD

**Issue by Sunainacode** [Sushreesatarupa/DSA-cpp#311]
### Description

C++ code for level order traversal in binary search tree

### Domain

Binary Search Tree

### Type of Contribution

Code

### Code of Conduct

- [X] I follow Contributing Guidelines & Code of conduct.

**Comment by madildev** [comment]
I will like to handle this issue. Assign me this issue

**Comment by Sunainacode** [comment]
@madildev I have already worked on this issue and created a PR :D

**Comment by SahbanAlam** [comment]
I have a good knowledge of DSA. Please assign me this issue
