### ISSUE TITLE
Join two linked lists

### ISSUE THREAD

**Issue by pawangupta5167** [Sushreesatarupa/DSA-cpp#312]
### Description

Hey, i want to add a program for joining two linked lists.Please assign it to me under Hacktoberfest.

### Domain

Linked List

### Type of Contribution

Code

### Code of Conduct

- [X] I follow Contributing Guidelines & Code of conduct.

**Comment by AbhayG01** [comment]
I have good knowledge of Data Structures and Algorithms, please assign this issue to me.

**Comment by Roshan5401** [comment]
Sir please assign me this problem i will do it in a better way and less time complexity.

**Comment by SahbanAlam** [comment]
Sir I have a good knowledge of DSA. Please assign me this issue
