### ISSUE TITLE
Solution to binary combination problem

### ISSUE THREAD

**Issue by gayatri517** [Sushreesatarupa/DSA-cpp#32]
I would like to add the code to special binary combination Interview problem in C++ in the recursion folder for Hacktoberfest 2021. Kindly accept my pull request.

**Comment by navjotdadwal** [comment]
sir can you please assign this issue to me i am current rated 5 star at codechef with rating of 2153 and rated expert at codeforces with rating of 1776 and i use cpp language for competitive programming and can resolve this issue
