### ISSUE TITLE
Program to find GCD of 2 numbers

### ISSUE THREAD

**Issue by Aarushijain-06** [Sushreesatarupa/DSA-cpp#324]
### Description

I will add the program for finding the GCD of 2 numbers.

### Domain

Mathematics

### Type of Contribution

Code With Explanation

### Code of Conduct

- [X] I follow Contributing Guidelines & Code of conduct.

**Comment by Raya513** [comment]
Please assign this issue to me I am skilled in data structures and algorithm.

**Comment by SahbanAlam** [comment]
Sir can you please assign me this issue. I have a good knowledge of DSA
