### ISSUE TITLE
Array Representation of BST

### ISSUE THREAD

**Issue by priya03ranjan01** [Sushreesatarupa/DSA-cpp#344]
### Description

Want to contribute to the underrated topic of array representation of BST along with implementation of deletion, insertion and searching in the same, to serve as an asset under Hacktoberfest.

### Domain

Binary Search Tree

### Type of Contribution

Code

### Code of Conduct

- [X] I follow Contributing Guidelines & Code of conduct.

**Comment by mephi007** [comment]
Hi, I would like to contribute. Please assign

**Comment by madildev** [comment]
I would like to contribute to. Ca you please assign me this issue

**Comment by madildev** [comment]
I would like to contribute too. Can you please assign this to me
