### ISSUE TITLE
Mirror Tree of a given Binary Tree

### ISSUE THREAD

**Issue by rijusougata13** [Sushreesatarupa/DSA-cpp#355]
Description
Output Mirror Tree of a given Binary Tree

Domain
Binary Tree

Type of Contribution
Code

**Comment by sbhavya18** [comment]
please assign this issue too me

Description
Output Mirror Tree of a Binary tree

Domain
Binary Tree

Contribution Type
Code

Language 
C++

**Comment by Raya513** [comment]
Please assign this issue to me I am skilled in data structures and algorithm.

**Comment by SahbanAlam** [comment]
I have a good knowledge of DSA. Please assign me this issue

**Comment by Roshan5401** [comment]
Please assign me this problem i have a good knowledge in c++ and can explain every step in comments.

**Comment by rijusougata13** [comment]
hi @Sushreesatarupa  why this issue is closed ?  as my PR isn't merged yet
