### ISSUE TITLE
[Create New Issue]: doubly linked list

### ISSUE THREAD

**Issue by 124015001** [Sushreesatarupa/DSA-cpp#364]
### Description

Implemented doubly linked list algorithm. Operations performed are insertion, deletion and searching. Also, kept in mind various logics such as full list, empty list, and circular linked list.

### Domain

Linked List

### Type of Contribution

Code

### Code of Conduct

- [X] I follow Contributing Guidelines & Code of conduct.

**Comment by 124015001** [comment]
Assign me this issue.

**Comment by madildev** [comment]
I am proficient in Algorithms and Data Structures. Assign me this issue.
