### ISSUE TITLE
Solution to Edit Distance Problem Dynamic Programming 

### ISSUE THREAD

**Issue by pranshukas** [Sushreesatarupa/DSA-cpp#37]
I would like to add the Solution to the Edit Distance problem in C++ in the Dynamic Programming folder for Hacktoberfest 2021. Kindly assign me this issue to work upon. 
Kindly add the HacktoberFest Label !
I am new to open source and keen to learn.

**Comment by navjotdadwal** [comment]
sir can you please assign this issue to me i am current rated 5 star at codechef with rating of 2153 and rated expert at codeforces with rating of 1776 and i use cpp language for competitive programming and can resolve this issue
