### ISSUE TITLE
Lowest Common Ancestor of a Binary Tree

### ISSUE THREAD

**Issue by rajbir21-droid** [Sushreesatarupa/DSA-cpp#408]
### Description

Given a binary tree, find the lowest common ancestor (LCA) of two given nodes in the tree.

According to the definition of LCA on Wikipedia: “The lowest common ancestor is defined between two nodes p and q as the lowest node in T that has both p and q as descendants (where we allow a node to be a descendant of itself).”

I am a contributor in hacktoberfest 2021.
Please assign me this issue
I want to work on it
Thank you

### Domain

Tree

### Type of Contribution

Code

### Code of Conduct

- [X] I follow Contributing Guidelines & Code of conduct.

**Comment by piyush26arora** [comment]
Hey I'm ready to take up this issue, just solved it yesterday !!!
You can assign it to me :)

**Comment by Ayaan2907** [comment]
@rajbir21-droid  Hi can I take this? I am ready with the submission.

**Comment by jainsanyam228** [comment]
hello I just complete maximum tree que in leetcode and gfg  .
You can assign it to me 👍

**Comment by rajbir21-droid** [comment]
I have created this issue for myself as I am participating in Hacktoberfest .

**Comment by Ayaan2907** [comment]
#441  please consider this.
