### ISSUE TITLE
Delete the middle node of a Linked List

### ISSUE THREAD

**Issue by RADHIKA-JOSHI123** [Sushreesatarupa/DSA-cpp#429]
### Description
Cpp code to delete the middle the element of the Linked List.
If the length of the linked list is odd then delete (( n+1)/2)th term of the linked list and if the list is of even length then delete the (n/2+1)th term of the liked list.

### Domain

Linked List

### Type of Contribution

Code

### Code of Conduct

- [X] I follow Contributing Guidelines & Code of conduct.

**Comment by ishaan49k** [comment]
i can do this. Please assign it to me. You can see my github repos. I have already solved many problems similar to this

**Comment by NavalMahajan** [comment]
please assign me this .i started dsa  recently. i would like to test my skills

**Comment by Roshan5401** [comment]
Please assign me this problem i have a good knowledge in DSA and i would like to do it.
