### ISSUE TITLE
[Stack] Remove All Adjacent Duplicates In String

### ISSUE THREAD

**Issue by Zignake** [Sushreesatarupa/DSA-cpp#447]
### Description

You are given a string s consisting of lowercase English letters. A duplicate removal consists of choosing two adjacent and equal letters and removing them.

We repeatedly make duplicate removals on s until we no longer can.

Return the final string after all such duplicate removals have been made. It can be proven that the answer is unique.

 

Example 1:
```
Input: s = "abbaca"
Output: "ca"
Explanation: 
For example, in "abbaca" we could remove "bb" since the letters are adjacent and equal, and this is the only possible move.  The result of this move is that the string is "aaca", of which only "aa" is possible, so the final string is "ca".
```
Example 2:
```
Input: s = "azxxzy"
Output: "ay"
```

### Domain

Stacks

### Type of Contribution

Code

### Code of Conduct

- [X] I follow Contributing Guidelines & Code of conduct.

**Comment by AmeyaKulkarni2001** [comment]
I can try this question, I have practiced a lot of questions on stack, and I feel that I can do this question

Basic Logic
Take a pointer
Push the first element in the array
then compare the next letter in the string with the element in the stack
if they are same pop the element
or else add the element
