### ISSUE TITLE
0-1 Knapsack Problem

### ISSUE THREAD

**Issue by ishaan49k** [Sushreesatarupa/DSA-cpp#449]
I would love to contribute the code of 0-1 knapsack and explain it thoroughly with documentation.

I am a participand of hacktoberfest 2021

**Comment by KislaySingh10** [comment]
Hey, I would like to contribute to this issue. I will provide the proper code with comments and documentation with both bottom up approach and top down approach.
Please assign this to me.

**Comment by SahbanAlam** [comment]
I have a good knowledge of DSA. I would love to contribute to this issue.
