### ISSUE TITLE
Linear Search

### ISSUE THREAD

**Issue by kavania2002** [Sushreesatarupa/DSA-cpp#453]
**Is your feature request related to a problem? Please describe.**
I went through the search folder and found that there is no linear search.

**Describe the solution you'd like**
I would like to add a C++ code for the linear search

**Comment by NavalMahajan** [comment]
please assign me this issue i would love to code linear search

**Comment by SahilRout** [comment]
okay i would like to implement it I can also add comments explaining the code pls assign it to me

**Comment by Roshan5401** [comment]
Please assign me this problem i have a good knowledge in c++ and can explain every step in comments.

**Comment by SahbanAlam** [comment]
I have a good knowledge of DSA. Please assign me this issue
