### ISSUE TITLE
Detect loop in a linked list

### ISSUE THREAD

**Issue by Abhas-15** [Sushreesatarupa/DSA-cpp#454]
### Description

Hey @Sushreesatarupa I would like to work on this.Please assign it to me.

### Domain

Linked List

### Type of Contribution

Code

### Code of Conduct

- [X] I follow Contributing Guidelines & Code of conduct.

**Comment by NavalMahajan** [comment]
please assign me this issue . i would love to do this

**Comment by SahilRout** [comment]
I have Done this question i can also add comments explaining the code pls assign it to me

**Comment by R-Ayush777** [comment]
Sir, Please assign me this issue. This is something I'd really like to do.
