### ISSUE TITLE
Rotate a linked List

### ISSUE THREAD

**Issue by divya-rai-42** [Sushreesatarupa/DSA-cpp#486]
### Description

Given a linked list, rotate it k times to the left.

### Domain

Linked List

### Type of Contribution

Code

### Code of Conduct

- [X] I follow Contributing Guidelines & Code of conduct.

**Comment by inabinash** [comment]
I will work on it.

**Comment by divya-rai-42** [comment]
@Sushreesatarupa  Please assign me this issue.
