### ISSUE TITLE
Majority Element

### ISSUE THREAD

**Issue by Aryan-Srivastava** [Sushreesatarupa/DSA-cpp#490]
### Description

Will be adding brute, better and optimal solution for the [Majority element](https://leetcode.com/problems/majority-element/) problem with explanation.

### Domain

Searching

### Type of Contribution

Code With Explanation

### Code of Conduct

- [X] I follow Contributing Guidelines & Code of conduct.

**Comment by gouravgouravgupta** [comment]
Please assign this to me
