### ISSUE TITLE
Reverse a stack using recursion

### ISSUE THREAD

**Issue by AmitThakur045** [Sushreesatarupa/DSA-cpp#495]
### Description
Write a recursive approach(code) to reverse a stack

### Domain

Stacks

### Type of Contribution

Code

### Code of Conduct

- [X] I follow Contributing Guidelines & Code of conduct.

**Comment by ayush523** [comment]
Hi, I would like to work on this issue.

**Comment by Octet3290** [comment]
Hello, I would like to do this issue.
Kindly assign this to me !
