### ISSUE TITLE
 Kth Largest Element in an Array

### ISSUE THREAD

**Issue by jainsanyam228** [Sushreesatarupa/DSA-cpp#509]
### Description

Given an integer array nums and an integer k, return the kth largest element in the array.

Note that it is the kth largest element in the sorted order, not the kth distinct element.

### Domain

Heap

### Type of Contribution

Code

### Code of Conduct

- [X] I follow Contributing Guidelines & Code of conduct.

**Comment by jainsanyam228** [comment]
@Sushreesatarupa Kindly please assign me this issue
#hacktoberfest21

**Comment by isharawat** [comment]
claim

**Comment by gouravgouravgupta** [comment]
@Sushreesatarupa  please assign to me
