### ISSUE TITLE
Linked list

### ISSUE THREAD

**Issue by AmalSN** [Sushreesatarupa/DSA-cpp#81]
I would like to contribute a code to reverse a linked list. Please assign this to me!

**Comment by a-sambhab** [comment]
Hey, @Sushreesatarupa, I would like to contribute to the rotate-a-linked-list. Please assign it to me

**Comment by Harshgoel189** [comment]
Hello,I would like to propose the solution of "remove duplicates from the linked List".Please assign it to me.

**Comment by a-sambhab** [comment]
hey, @Sushreesatarupa, do review pr #315 for the above assigned task
