### ISSUE TITLE
Adding merge Sort Solution

### ISSUE THREAD

**Issue by Yash-Sakre** [Sushreesatarupa/DSA-cpp#94]
I would like to work on a Problem statement [Merge sort](https://practice.geeksforgeeks.org/problems/merge-sort/1/)

Requesting to be assigned to this issue under the 'hacktoberfest2021' label.

Please assign me this issue.

**Comment by waryphantom** [comment]
i am really looking forward for my first contribution in open source....please! assign it to me.

**Comment by Yash-Sakre** [comment]
hey, @Sayansree Please Assign me this issue as a Hactoberfest Contributor.
